"""create p3 business schema

Revision ID: cdb0d35109b0
Revises:
Create Date: 2026-09-16 04:13:12.261379
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cdb0d35109b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "after_sales_rules",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("rule_code", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("request_type", sa.String(length=24), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("allowed_conditions", sa.JSON(), nullable=False),
        sa.Column("excluded_reason_codes", sa.JSON(), nullable=False),
        sa.Column("required_materials", sa.JSON(), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_code"),
    )
    op.create_index(
        op.f("ix_after_sales_rules_category"), "after_sales_rules", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_after_sales_rules_request_type"),
        "after_sales_rules",
        ["request_type"],
        unique=False,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("document_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("source_uri", sa.String(length=500), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_sha256"),
    )
    op.create_table(
        "knowledge_versions",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("brand", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("usage_tags", sa.JSON(), nullable=False),
        sa.Column("audience_tags", sa.JSON(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("sales_count", sa.Integer(), nullable=False),
        sa.Column("data_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_brand"), "products", ["brand"], unique=False)
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("masked_phone", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_ref"),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("graph_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=48), nullable=False),
        sa.Column("case_id", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Numeric(precision=8, scale=5), nullable=True),
        sa.Column("error_type", sa.String(length=80), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_run_id", "case_id", name="uq_eval_result_run_case"),
    )
    op.create_index(
        op.f("ix_evaluation_results_evaluation_run_id"),
        "evaluation_results",
        ["evaluation_run_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index("ix_orders_user_created", "orders", ["user_id", "created_at"], unique=False)
    op.create_table(
        "skus",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("product_id", sa.String(length=40), nullable=False),
        sa.Column("sku_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("color", sa.String(length=40), nullable=False),
        sa.Column("specifications_json", sa.JSON(), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("price_valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku_code"),
    )
    op.create_index(op.f("ix_skus_price_snapshot_id"), "skus", ["price_snapshot_id"], unique=False)
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("session_id", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("graph_version", sa.String(length=40), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("tool_schema_version", sa.String(length=16), nullable=False),
        sa.Column("rule_version", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("decision_summary", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_agent_runs_session_id"), "agent_runs", ["session_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_trace_id"), "agent_runs", ["trace_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("session_id", sa.String(length=48), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content_redacted", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_session_created",
        "chat_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=40), nullable=False),
        sa.Column("warehouse", sa.String(length=80), nullable=False),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku_id", "region", name="uq_inventory_sku_region"),
    )
    op.create_index(op.f("ix_inventory_sku_id"), "inventory", ["sku_id"], unique=False)
    op.create_table(
        "logistics_events",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("carrier", sa.String(length=40), nullable=False),
        sa.Column("tracking_number_masked", sa.String(length=48), nullable=False),
        sa.Column("status_code", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "sequence", name="uq_logistics_order_sequence"),
    )
    op.create_index(
        op.f("ix_logistics_events_order_id"), "logistics_events", ["order_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("product_id", sa.String(length=40), nullable=False),
        sa.Column("sku_id", sa.String(length=40), nullable=False),
        sa.Column("name_snapshot", sa.String(length=180), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_snapshot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal_snapshot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("item_condition", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_order_items_order", "order_items", ["order_id"], unique=False)
    op.create_table(
        "service_tickets",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("principal_id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=48), nullable=False),
        sa.Column("request_type", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=False),
        sa.Column("description_redacted", sa.String(length=1000), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("approval_status", sa.String(length=40), nullable=False),
        sa.Column("refund_amount_snapshot", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["order_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["principal_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_fingerprint", name="uq_ticket_fingerprint"),
        sa.UniqueConstraint("principal_id", "idempotency_key", name="uq_ticket_principal_idem"),
    )
    op.create_index(
        op.f("ix_service_tickets_order_id"), "service_tickets", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_tickets_principal_id"), "service_tickets", ["principal_id"], unique=False
    )
    op.create_table(
        "tool_call_logs",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("tool_call_id", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments_summary", sa.JSON(), nullable=False),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_call_id"),
    )
    op.create_index(op.f("ix_tool_call_logs_run_id"), "tool_call_logs", ["run_id"], unique=False)
    op.create_table(
        "approval_tasks",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("ticket_id", sa.String(length=48), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("amount_snapshot", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["service_tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("approval_tasks")
    op.drop_index(op.f("ix_tool_call_logs_run_id"), table_name="tool_call_logs")
    op.drop_table("tool_call_logs")
    op.drop_index(op.f("ix_service_tickets_principal_id"), table_name="service_tickets")
    op.drop_index(op.f("ix_service_tickets_order_id"), table_name="service_tickets")
    op.drop_table("service_tickets")
    op.drop_index("ix_order_items_order", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_logistics_events_order_id"), table_name="logistics_events")
    op.drop_table("logistics_events")
    op.drop_index(op.f("ix_inventory_sku_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index("ix_chat_messages_session_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_agent_runs_trace_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_session_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_price_snapshot_id"), table_name="skus")
    op.drop_table("skus")
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_evaluation_results_evaluation_run_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index(op.f("ix_products_brand"), table_name="products")
    op.drop_table("products")
    op.drop_table("knowledge_versions")
    op.drop_table("knowledge_documents")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_after_sales_rules_request_type"), table_name="after_sales_rules")
    op.drop_index(op.f("ix_after_sales_rules_category"), table_name="after_sales_rules")
    op.drop_table("after_sales_rules")
    # ### end Alembic commands ###
